const SPECIALTIES={'cardio-intervencion':'Cardio Intervención','neuro-intervencion':'Neuro Intervención','vascular-periferico':'Vascular Periférico'};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const icon=(type='arrow')=>{const paths={arrow:'<path d="M7 17 17 7M7 7h10v10"/>',search:'<circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/>',file:'<path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8zM14 2v6h6M8 13h8M8 17h5"/>',download:'<path d="M12 3v12m-5-5 5 5 5-5M5 16v5h14v-5"/>'};return `<svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[type]}</svg>`};
const app=document.getElementById('app');let state={specialty:'all',q:'',category:'all',brand:'all',pdf:false,asahiType:'all',guideGroup:'all',philipsType:'all'};let lastCatalog='#/';
const counts=key=>PRODUCTS.filter(p=>p.specialty===key).length;
function catalogURL(){const params=new URLSearchParams();Object.entries(state).forEach(([k,v])=>{if(v&&v!=='all')params.set(k,String(v))});return '#/'+(params.size?'?'+params:'')}
function saveFilters(){lastCatalog=catalogURL();history.replaceState(null,'',lastCatalog)}
function image(p,extra=''){return p.image?`<img src="${esc(p.image)}" alt="${esc(p.imageAlt||p.name)}" loading="lazy" ${extra}>`:`<span class="fallback-image">${esc(p.name)}</span>`}
function card(p){return `<article class="product-card"><a class="product-picture" href="#/producto/${p.slug}" aria-label="Ver ${esc(p.name)}">${image(p)}</a><div class="card-body"><span class="brand">${esc(p.brand)}</span><h3><a href="#/producto/${p.slug}">${esc(p.name)}</a></h3><p class="category-label">${esc(p.category)}</p>${p.tipLoad!==undefined?`<span class="tip-badge">Punta: ${p.tipLoad} gf</span>`:''}${p.useCase?`<p class="card-use">${esc(p.useCase)}</p>`:''}<div class="card-footer"><a class="card-link" href="#/producto/${p.slug}">Ver ficha ↗</a>${p.pdfs.length?`<a class="pdf-link" href="${esc(p.pdfs[0].path)}" target="_blank" rel="noopener" aria-label="Abrir PDF de ${esc(p.name)}">${icon('file')} PDF</a>`:'<span style="color:var(--muted)">Ficha web</span>'}</div></div></article>`}
function specialtyTabs(){return `<div class="specialty-tabs" role="group" aria-label="Especialidad"><button class="tab ${state.specialty==='all'?'active':''}" data-specialty="all" aria-pressed="${state.specialty==='all'}">Todos <span>${PRODUCTS.length}</span></button>${Object.entries(SPECIALTIES).map(([k,v])=>`<button class="tab ${state.specialty===k?'active':''}" data-specialty="${k}" aria-pressed="${state.specialty===k}">${v}<span>${counts(k)}</span></button>`).join('')}</div>`}
function categories(){const map=new Map();PRODUCTS.filter(p=>state.specialty==='all'||p.specialty===state.specialty).forEach(p=>p.categories.forEach(c=>{if(!map.has(c.slug))map.set(c.slug,{...c,count:0});map.get(c.slug).count++}));return [...map.values()].sort((a,b)=>a.name.localeCompare(b.name,'es'))}
function catalog(){const cats=categories();const brands=[...new Set(PRODUCTS.map(p=>p.brand))].sort();return `<section class="intro container page-enter"><div class="intro-row"><div><span class="eyebrow">AlfaCor · Biblioteca de productos</span><h1>La ficha que necesitás.<br>A mano.</h1><p>Dispositivos, características y documentos técnicos, organizados por especialidad.</p></div><div class="numbers"><div><b>${PRODUCTS.length}</b><span>Productos</span></div><div><b>${brands.length}</b><span>Marcas</span></div><div><b>03</b><span>Especialidades</span></div></div></div><div class="searchbar">${icon('search')}<input id="search" type="search" value="${esc(state.q)}" aria-label="Buscar productos" placeholder="Buscá un producto, marca o característica…" autocomplete="off"><button class="clear-search" id="clearSearch" aria-label="Borrar búsqueda" ${!state.q?'hidden':''}>×</button></div>${specialtyTabs()}</section><section class="container catalog-layout"><aside class="filters" aria-label="Filtros de productos"><div class="filter-section"><h3>Categoría</h3><div class="category-list"><button class="category-button ${state.category==='all'?'active':''}" data-category="all">Todas las categorías</button>${cats.map(c=>`<button class="category-button ${state.category===c.slug?'active':''}" data-category="${c.slug}">${esc(c.name)} <span>${c.count}</span></button>`).join('')}</div><label class="mobile-filter-label"><select id="categorySelect" aria-label="Categoría"><option value="all">Todas las categorías</option>${cats.map(c=>`<option value="${c.slug}" ${state.category===c.slug?'selected':''}>${esc(c.name)}</option>`).join('')}</select></label></div><div class="filter-section"><h3>Marca</h3><select id="brandSelect" aria-label="Marca"><option value="all">Todas las marcas</option>${brands.map(b=>`<option value="${esc(b)}" ${state.brand===b?'selected':''}>${esc(b)}</option>`).join('')}</select></div><label class="check-label"><input id="pdfOnly" type="checkbox" ${state.pdf?'checked':''}>Con PDF disponible</label><button class="reset" id="resetFilters">Limpiar filtros</button></aside><div><div class="results-head"><h2>${SPECIALTIES[state.specialty]||'Todos los productos'}</h2><span id="resultCount" role="status" aria-live="polite"></span></div>${asahiControls()}${philipsControls()}<div class="product-grid" id="results"></div><div id="philipsCases"></div><div id="empty" class="empty" hidden><h3>No encontramos productos</h3><p>Probá otro nombre o quitá algún filtro.</p><button class="button" id="emptyReset">Ver todos los productos</button></div></div></section>`}
function filtered(){return PRODUCTS.filter(p=>(state.specialty==='all'||p.specialty===state.specialty)&&(state.category==='all'||p.categories.some(c=>c.slug===state.category))&&(state.brand==='all'||p.brand===state.brand)&&(state.asahiType==='all'||p.asahiGroup===state.asahiType)&&(state.guideGroup==='all'||p.guideGroup===state.guideGroup)&&(state.philipsType==='all'||p.philipsGroup===state.philipsType)&&(!state.pdf||p.pdfs.length)&&norm([p.name,p.brand,p.category,p.quickType,p.useCase||'',p.quickSpecs.flat().join(' ')].join(' ')).includes(norm(state.q.trim()))).sort((a,b)=>a.name.localeCompare(b.name,'es'))}
function updateResults(){const ps=filtered();document.getElementById('results').innerHTML=catalogCards(ps);document.getElementById('philipsCases').innerHTML=/philips/i.test(state.brand)&&ps.some(p=>p.philipsGroup==='coronary')?philipsCases():'';document.getElementById('resultCount').textContent=`${ps.length} ${ps.length===1?'producto':'productos'}`;document.getElementById('empty').hidden=ps.length>0;document.getElementById('clearSearch').hidden=!state.q;saveFilters()}
function bindCatalog(){document.querySelectorAll('[data-philips-type]').forEach(b=>b.onclick=()=>{state.philipsType=b.dataset.philipsType;state.category='all';redrawCatalog()});document.querySelectorAll('[data-asahi-type]').forEach(b=>b.onclick=()=>{state.asahiType=b.dataset.asahiType;state.guideGroup='all';state.category='all';redrawCatalog()});document.querySelectorAll('[data-guide-group]').forEach(b=>b.onclick=()=>{state.guideGroup=b.dataset.guideGroup;redrawCatalog()});document.getElementById('search').addEventListener('input',e=>{state.q=e.target.value;updateResults()});document.getElementById('clearSearch').onclick=()=>{state.q='';document.getElementById('search').value='';updateResults();document.getElementById('search').focus()};document.querySelectorAll('[data-specialty]').forEach(b=>b.onclick=()=>{state.specialty=b.dataset.specialty;state.category='all';redrawCatalog()});document.querySelectorAll('[data-category]').forEach(b=>b.onclick=()=>{state.category=b.dataset.category;redrawCatalog()});document.getElementById('categorySelect').onchange=e=>{state.category=e.target.value;updateResults()};document.getElementById('brandSelect').onchange=e=>{state.brand=e.target.value;state.philipsType='all';state.asahiType='all';state.guideGroup='all';redrawCatalog()};document.getElementById('pdfOnly').onchange=e=>{state.pdf=e.target.checked;updateResults()};const reset=()=>{state={specialty:'all',q:'',category:'all',brand:'all',pdf:false,asahiType:'all',guideGroup:'all',philipsType:'all'};redrawCatalog()};document.getElementById('resetFilters').onclick=reset;document.getElementById('emptyReset').onclick=reset;updateResults()}
function redrawCatalog(){app.innerHTML=catalog();bindCatalog()}
function quickSpecs(p){return `<dl class="quick-specs">${p.quickSpecs.map(([label,value])=>`<div class="quick-row"><dt>${esc(label)}</dt><dd>${esc(value)}</dd></div>`).join('')}</dl>`}
function clinicalTable(headers,rows,caption){return `<div class="table-scroll" tabindex="0" role="region" aria-label="${esc(caption)}"><table class="clinical-table"><caption>${esc(caption)}</caption><thead><tr>${headers.map(x=>`<th scope="col">${esc(x)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map((x,i)=>i===0?`<th scope="row">${esc(x)}</th>`:`<td>${esc(x)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
function expansionPanel(p){return `<section class="expansion-panel"><div class="expansion-title"><h3>Expansión máxima observada</h3><span>Diámetro externo · O.D.</span></div><div class="expansion-grid">${p.expansionInfo.rows.map(r=>`<div class="expansion-measure"><span class="expansion-size">Stent Ø ${esc(r.diameters)} mm</span><strong>${esc(r.maximum)} <small>mm</small></strong><p>BioMatrix Alpha ${esc(r.sample)} mm · n = 1<br>Balón de ${esc(r.balloon)} mm a presión nominal</p></div>`).join('')}</div><p class="table-note">Ensayo in vitro de muestra limitada sobre BioMatrix Alpha, citado por Biosensors para BioFreedom Ultra. Valores experimentales de diámetro externo; no son límites clínicos de posdilatación.</p><a class="source-link" href="https://www.biosensors.com/intl/sites/default/files/12161-000-en_32201_ultbro_main_210x297_r03d2_lr.pdf" target="_blank" rel="noopener">Biosensors · BioFreedom Ultra, sobreexpansión ↗</a></section>`}
const PHILIPS_TYPES={coronary:'Imagen y fisiología coronaria',peripheral:'IVUS periférico',extraction:'Extracción de electrodos'};
function philipsControls(){if(!/philips/i.test(state.brand))return '';return `<nav class="asahi-browser" aria-label="Familias Philips"><div class="asahi-options"><button data-philips-type="all" aria-pressed="${state.philipsType==='all'}">Todo Philips</button>${Object.entries(PHILIPS_TYPES).map(([k,v])=>`<button data-philips-type="${k}" aria-pressed="${state.philipsType===k}">${v}</button>`).join('')}</div></nav>`}
const ASAHI_TYPES={microcatheters:'Microcatéteres',guides:'Guías',catheters:'Catéteres'};
const GUIDE_GROUPS={frontline:'Línea frontal',cto:'Crónicas · CTO',retrograde:'Retrógradas',peripheral:'Periféricas'};
function asahiControls(){if(!/asahi/i.test(state.brand))return '';return `<nav class="asahi-browser" aria-label="Familias Asahi"><div class="asahi-options"><button data-asahi-type="all" aria-pressed="${state.asahiType==='all'}">Todo Asahi</button>${Object.entries(ASAHI_TYPES).map(([k,v])=>`<button data-asahi-type="${k}" aria-pressed="${state.asahiType===k}">${v}</button>`).join('')}</div>${state.asahiType==='guides'?`<div class="guide-options" role="group" aria-label="Tipos de guías"><button data-guide-group="all" aria-pressed="${state.guideGroup==='all'}">Todas las guías</button>${Object.entries(GUIDE_GROUPS).map(([k,v])=>`<button data-guide-group="${k}" aria-pressed="${state.guideGroup===k}">${v}</button>`).join('')}</div>`:''}</nav>`}
function catalogCards(ps){const heading=(title,items)=>items.length?`<div class="product-group-heading"><h2>${title}</h2><span>${items.length} productos</span></div>${items.map(card).join('')}`:'';return ps.filter(p=>!p.asahiGroup&&!p.philipsGroup).map(card).join('')+Object.entries(PHILIPS_TYPES).map(([key,title])=>heading('Philips · '+title,ps.filter(p=>p.philipsGroup===key))).join('')+Object.entries(ASAHI_TYPES).map(([key,title])=>{const items=ps.filter(p=>p.asahiGroup===key);return key==='guides'?Object.entries(GUIDE_GROUPS).map(([g,label])=>heading('Guías Asahi · '+label,items.filter(p=>p.guideGroup===g))).join(''):heading(title+' Asahi',items)}).join('')}
function stentInfo(p){if(!p.pressureInfo)return '';const info=p.pressureInfo;let extra='';if(p.compliance){const fmt=x=>x===null?'—':Number(x).toFixed(2).replace('.',',');const rows=rs=>rs.map(r=>[r[0]+(r[0]===8?' · NP':r[0]===14||r[0]===16?' · RBP*':''),...r.slice(1).map(fmt)]);extra=`<details class="technical-details"><summary>Ver tabla de distensibilidad por longitud</summary><p>Diámetro interno del stent en mm a cada presión del balón. No equivale al límite de posdilatación con otro balón.</p>${clinicalTable(['Presión (atm)','Ø 2,25','Ø 2,50','Ø 2,75','Ø 3,00','Ø 3,50','Ø 4,00'],rows(p.compliance.short),'Longitudes: 14, 19, 24 y 29 mm')}${clinicalTable(['Presión (atm)','Ø 2,50','Ø 2,75','Ø 3,00','Ø 3,50'],rows(p.compliance.long),'Longitudes: 33 y 36 mm')}<p class="table-note">* RBP: 14 atm para Ø 3,50–4,00 mm; 16 atm para Ø 2,25–3,00 mm. — = no utilizar: supera la RBP de esa medida.</p><a class="source-link" href="assets/ultra-tech.pdf#page=2" target="_blank" rel="noopener">Biosensors · ficha 12094-000-FR Rev.01c, p. 2 ↗</a></details>`;}return `<section class="technical-section"><h2>Presión nominal y de ruptura</h2><p>Balón del sistema de liberación · valores por diámetro y longitudes disponibles.</p>${clinicalTable(['Ø stent (mm)','Longitudes (mm)','Nominal · NP (atm)','Ruptura · RBP (atm)'],info.rows,'Presiones del balón de '+p.name)}<p class="table-note">RBP = presión de ruptura nominal especificada por el fabricante; no superar. No representa la presión de rotura exacta de cada balón.</p><a class="source-link" href="${esc(info.sourcePath)}" target="_blank" rel="noopener">Biosensors · IFU ${esc(info.sourceLabel)} ↗</a>${extra}${expansionPanel(p)}</section>`}
function productVideo(p){if(!p.video)return '';const v=p.video;return `<section class="technical-section"><h2>Video de implantación · ALLEGRA</h2><p>${esc(v.description)}</p><div class="product-video"><iframe src="https://www.youtube-nocookie.com/embed/${esc(v.id)}?rel=0" title="${esc(v.title)}" loading="lazy" referrerpolicy="strict-origin-when-cross-origin" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></div><div class="video-caption"><span>${esc(v.author)} · YouTube</span><a class="source-link" href="${esc(v.url)}" target="_blank" rel="noopener">Abrir en YouTube ↗</a></div><p class="table-note">Requiere internet. Material educativo para profesionales; consultá las instrucciones del sistema de liberación utilizado.</p></section>`}

function detail(p){return `<section class="container quick-page page-enter"><a class="back-link" href="${esc(lastCatalog)}">← Volver al catálogo</a><article class="quick-card"><div class="quick-heading"><div class="quick-image">${image(p)}</div><div><span class="brand">${esc(p.brand)}</span><h1>${esc(p.name)}</h1><p class="quick-type">${esc(p.quickType)}</p><span class="quick-specialty">${SPECIALTIES[p.specialty]}</span></div></div>${p.useCase?`<div class="use-case"><h2>¿En qué casos se utiliza?</h2><p>${esc(p.useCase)}</p></div>`:''}${quickSpecs(p)}${stentInfo(p)}${productVideo(p)}<div class="quick-bottom">${p.pdfs.length?`<a class="button small" href="${esc(p.pdfs[0].path)}" target="_blank" rel="noopener">${icon('file')} ${esc(p.pdfs[0].label||'Ficha completa')} · PDF</a>`:'<span class="pdf-note">PDF no disponible en el catálogo.</span>'}<a class="source-link" href="${esc(p.officialSource||p.source)}" target="_blank" rel="noopener">${p.officialSource?'Fabricante':'Fuente'} ↗</a></div></article>${[646,649,653].includes(p.id)?philipsCases():''}<p class="quick-note">${p.tipLoad!==undefined?'gf = gramos-fuerza de la punta; no indica el soporte del cuerpo. Usos orientativos. ':''}Confirmá la referencia y su compatibilidad en la documentación del fabricante.</p></section>`}
function philipsCases(){const videos=[{id:'SsnkJdkMw9E',title:'PCI compleja guiada por iFR e iFR Scout',author:'Radcliffe Cardiology · Justin Davies e Iqbal Malik',description:'Caso coronario en vivo grabado desde el Hammersmith Hospital: evaluación fisiológica para orientar una PCI compleja.',source:'https://www.radcliffecardiology.com/video-index/lfthh-live-case-simplifying-complex-pci'},{id:'Zdtx8uLrZ18',title:'iFR en enfermedad coronaria de tres vasos',author:'Philips Image Guided Therapy Devices · Imperial College, Londres',description:'Caso clínico de valoración de lesiones coronarias multivaso con iFR y guía de presión Verrata.',source:'https://www.philips.ua/en/healthcare/education-resources/technologies/igt/instant-wave-free-ratio'}];return `<section class="clinical-cases" aria-label="Casos coronarios Philips"><span class="eyebrow">Philips · Casos coronarios</span><h2>Fisiología en la práctica</h2><div class="coronary-videos">${videos.map(v=>`<article class="coronary-video-card"><h3>${esc(v.title)}</h3><p>${esc(v.description)}</p><div class="product-video"><iframe src="https://www.youtube-nocookie.com/embed/${v.id}?rel=0" title="${esc(v.title)}" loading="lazy" referrerpolicy="strict-origin-when-cross-origin" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></div><p class="video-caption">${esc(v.author)}</p><div class="video-links"><a class="source-link" href="https://www.youtube.com/watch?v=${v.id}" target="_blank" rel="noopener">Abrir en YouTube</a><a class="source-link" href="${v.source}" target="_blank" rel="noopener">Fuente del caso</a></div></article>`).join('')}</div><p class="table-note">Videos en inglés. Requieren internet.</p></section>`}
function brandPage(){const brands=[...new Set(PRODUCTS.map(p=>p.brand))].sort();return `<section class="container intro"><span class="eyebrow">Portafolio</span><h1>Explorá por marca.</h1><p>Todos sus dispositivos y documentos en un solo lugar.</p></section><section class="container brands-grid">${brands.map(b=>`<a class="brand-card" href="#/?brand=${encodeURIComponent(b)}"><span class="eyebrow">Fabricante</span><h2>${esc(b)}</h2><p>${PRODUCTS.filter(p=>p.brand===b).length} productos ↗</p></a>`).join('')}</section>`}
let quiz={phase:'setup',topic:'all',count:10,questions:[],index:0,answers:[]};
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function makeQuestion(p){
 let label,correct,alternatives,prompt;
 if(p.tipLoad!==undefined){label='Carga de punta';correct=p.tipLoad+' gf';alternatives=[...new Set(PRODUCTS.filter(x=>x.tipLoad!==undefined).map(x=>x.tipLoad+' gf'))].filter(x=>x!==correct);prompt=`¿Cuál es la carga de punta de ${p.name}${p.id===642?' (modelo estándar)':''}?`}
 else{const choices=p.quickSpecs.map(([l,v])=>({label:l,value:v,others:[...new Set(PRODUCTS.flatMap(x=>x.quickSpecs.filter(r=>r[0]===l).map(r=>r[1])))].filter(x=>x!==v)})).filter(x=>x.others.length>=3&&!/no especificadas/i.test(x.value));if(choices.length){const c=shuffle(choices)[0];label=c.label;correct=c.value;alternatives=c.others;prompt=`En ${p.name}, ¿qué dato corresponde a «${label}»?`}else{label='Fabricante';correct=p.brand;alternatives=[...new Set(PRODUCTS.map(x=>x.brand))].filter(x=>x!==correct);prompt=`¿Qué fabricante corresponde a ${p.name}?`}}
 return {productId:p.id,prompt,label,correct,options:shuffle([correct,...shuffle(alternatives).slice(0,3)]),explanation:`${p.name}: ${label.toLowerCase()} — ${correct}.${p.useCase?' '+p.useCase:''}`,source:p.officialSource||p.source};
}
function quizPool(topic){return PRODUCTS.filter(p=>topic==='all'||(topic==='asahi'?p.tipLoad!==undefined:p.specialty===topic))}
const CLINICAL_TOPICS={clinical:'IVUS y fisiología',ivus:'IVUS · Repaso completo',images:'IVUS · Identificación de imágenes',plaques:'IVUS · Placas y calcio',dissections:'IVUS · Disecciones y rotura de placa',stents:'IVUS · Stents y mediciones',physiology:'Fisiología coronaria · iFR y FFR'};
let studySpecialty='cardio-intervencion';
const STUDY_GROUPS={'cardio-intervencion':[['physiology','Fisiología coronaria','iFR, FFR, pullback y corregistro'],['images','IVUS · Identificar imágenes','Placas, calcio, disecciones, luces y stents'],['ivus','IVUS · Repaso completo','Interpretación, mediciones y preguntas visuales'],['cardio-intervencion','Insumos coronarios','Características de las fichas técnicas']], 'neuro-intervencion':[['neuro-intervencion','Insumos de neurointervención','Coils, microcatéteres y dispositivos del catálogo']], 'vascular-periferico':[['vascular-periferico','Insumos vasculares periféricos','Sondas, filtros y dispositivos del catálogo']], general:[['all','Todo el portafolio','Fichas de las tres especialidades'],['asahi','Guías Asahi','Carga de punta'],['philips','Productos Philips','Características técnicas'],['clinical','IVUS y fisiología','Todas las preguntas clínicas']]};
function clinicalPool(topic){return CLINICAL_QUESTIONS.filter(q=>topic==='clinical'||(topic==='ivus'?q.topic!=='physiology':topic==='images'?!!q.image:q.topic===topic))}
function questionCount(topic){return CLINICAL_TOPICS[topic]?clinicalPool(topic).length:topic==='philips'?PRODUCTS.filter(p=>p.philipsGroup).length:quizPool(topic).length}
function startQuiz(topic,count,retry){let pool;if(retry){pool=retry.map(q=>typeof q==='object'?q:makeQuestion(PRODUCTS.find(p=>p.id===q)))}else if(CLINICAL_TOPICS[topic]){pool=clinicalPool(topic)}else if(topic==='philips'){pool=PRODUCTS.filter(p=>p.philipsGroup).map(makeQuestion)}else{pool=quizPool(topic).map(makeQuestion)}quiz={phase:'question',topic,count,questions:shuffle(pool).slice(0,Math.min(count,pool.length)).map(q=>({...q,options:shuffle(q.options)})),index:0,answers:[]};render()}
function studySetup(){const topics=STUDY_GROUPS[studySpecialty];if(!topics.some(t=>t[0]===quiz.topic))quiz.topic=topics[0][0];return `<section class="container quiz-page study-setup"><span class="eyebrow">Modo estudio</span><h1>Elegí qué querés repasar.</h1><p>Preguntas por especialidad, con explicación y repaso de errores.</p><h2>1. Especialidad</h2><div class="study-specialties" role="group" aria-label="Especialidad de estudio">${Object.entries({...SPECIALTIES,general:'Repaso general'}).map(([k,v])=>`<button data-study-specialty="${k}" aria-pressed="${studySpecialty===k}">${esc(v)}</button>`).join('')}</div><h2>2. Apartado</h2><div class="study-topics" role="group" aria-label="Tema del cuestionario">${topics.map(([key,title,description])=>`<button class="study-topic" data-study-topic="${key}" aria-pressed="${quiz.topic===key}"><strong>${esc(title)}</strong><span>${esc(description)}</span><small>${questionCount(key)} preguntas</small></button>`).join('')}</div><div class="study-start"><label for="quizCount">3. Cantidad de preguntas</label><select id="quizCount"><option value="10">Hasta 10</option><option value="20">Hasta 20</option><option value="1000">Todas las del apartado</option></select><button id="startQuiz" class="button primary">Comenzar cuestionario</button></div>${studySpecialty==='cardio-intervencion'?`<div class="study-clinical-note"><h2>Practicá con imágenes reales</h2><p>25 preguntas de IVUS, incluidas 15 de identificación sobre 10 imágenes, y 12 de fisiología coronaria.</p><a class="source-link" href="assets/eagle-eye-interpretacion.pdf" target="_blank" rel="noopener">Guía de imágenes Philips · PDF</a><p class="table-note">Repaso educativo. Interpretá los hallazgos junto con las mediciones y el contexto clínico.</p></div>`:''}</section>`}
function chooseQuiz(value){if(quiz.phase!=='question'||quiz.answers[quiz.index])return;const q=quiz.questions[quiz.index];if(!q.options.includes(value))return;quiz.answers[quiz.index]={value,correct:value===q.correct};render()}
function nextQuiz(){if(!quiz.answers[quiz.index])return;if(quiz.index+1===quiz.questions.length)quiz.phase='results';else quiz.index++;render()}
function studyPage(){
 if(quiz.phase==='setup')return studySetup();
 if(quiz.phase==='results'){const score=quiz.answers.filter(a=>a.correct).length;const misses=quiz.questions.filter((q,i)=>!quiz.answers[i]?.correct);return `<section class="container quiz-page"><span class="eyebrow">Cuestionario completado</span><h1>${score} de ${quiz.questions.length} correctas</h1><p>${Math.round(score/quiz.questions.length*100)}% de aciertos. ${misses.length?'Repasá estas respuestas antes de volver a intentarlo.':'Completaste la ronda sin errores.'}</p><div class="quiz-actions"><button class="button primary" id="newQuiz">Nuevo cuestionario</button>${misses.length?'<button class="button" id="retryMissed">Repetir las falladas</button>':''}</div>${misses.map(q=>{const p=PRODUCTS.find(p=>p.id===q.productId);return `<article class="quiz-review"><h2>${esc(q.prompt)}</h2><p>Tu respuesta: <strong>${esc(quiz.answers[quiz.questions.indexOf(q)].value)}</strong></p><p>Respuesta correcta: <strong>${esc(q.correct)}</strong></p><p>${esc(q.explanation)}</p><a href="${esc(q.source)}" target="_blank" rel="noopener">Consultar explicación en la fuente ↗</a></article>`}).join('')}</section>`}
 const q=quiz.questions[quiz.index],p=PRODUCTS.find(p=>p.id===q.productId),a=quiz.answers[quiz.index];return `<section class="container quiz-page"><div class="quiz-top"><span>Pregunta ${quiz.index+1} de ${quiz.questions.length}</span><span>${quiz.answers.filter(a=>a.correct).length} aciertos</span></div><progress aria-label="Preguntas contestadas" value="${quiz.answers.length}" max="${quiz.questions.length}"></progress><article class="quiz-panel"><span class="eyebrow">${esc(q.clinical?CLINICAL_TOPICS[q.topic]:SPECIALTIES[p.specialty])}</span><h1 class="quiz-question">${esc(q.prompt)}</h1>${q.image?`<figure class="quiz-clinical-image"><img src="${esc(q.image)}" alt="${esc(q.imageAlt)}"><figcaption>${esc(q.imageCredit)}</figcaption></figure>`:''}${q.hint?`<details class="quiz-hint"><summary>Ver pista</summary><p>${esc(q.hint)}</p></details>`:''}<div class="quiz-options">${q.options.map((option,i)=>{const right=a&&option===q.correct,wrong=a&&a.value===option&&!a.correct;return `<button class="quiz-option ${right?'correct':wrong?'incorrect':''}" data-option="${i}" ${a?'disabled':''}><span class="option-letter">${'ABCD'[i]}</span><span>${esc(option)}</span>${right?'<span class="option-verdict">✓ Correcta</span>':wrong?'<span class="option-verdict">✕ Tu respuesta</span>':''}</button>`}).join('')}</div>${a?`<div class="quiz-feedback ${a.correct?'success':'error'}" role="status"><strong>${a.correct?'¡Correcto!':'La respuesta correcta es '+esc(q.correct)+'.'}</strong><p>${esc(q.explanation)}</p><a href="${esc(q.source)}" target="_blank" rel="noopener">Consultar fuente ↗</a></div><button class="button primary" id="nextQuestion">${quiz.index+1===quiz.questions.length?'Ver resultado':'Siguiente pregunta →'}</button>`:'<p class="quiz-instruction">Seleccioná una respuesta.</p>'}</article></section>`;
}
function bindQuiz(){if(quiz.phase==='setup'){document.querySelectorAll('[data-study-specialty]').forEach(b=>b.onclick=()=>{studySpecialty=b.dataset.studySpecialty;quiz.topic=STUDY_GROUPS[studySpecialty][0][0];render()});document.querySelectorAll('[data-study-topic]').forEach(b=>b.onclick=()=>{quiz.topic=b.dataset.studyTopic;render()});document.getElementById('quizCount').value=String([10,20,1000].includes(quiz.count)?quiz.count:10);document.getElementById('quizCount').onchange=e=>{quiz.count=Number(e.target.value)};document.getElementById('startQuiz').onclick=()=>startQuiz(quiz.topic,Number(document.getElementById('quizCount').value))}else if(quiz.phase==='results'){document.getElementById('newQuiz').onclick=()=>{quiz.phase='setup';render()};const retry=document.getElementById('retryMissed');if(retry)retry.onclick=()=>{const missed=quiz.questions.filter((q,i)=>!quiz.answers[i].correct);startQuiz(quiz.topic,missed.length,missed)}}else{document.querySelectorAll('[data-option]').forEach(b=>b.onclick=()=>chooseQuiz(quiz.questions[quiz.index].options[Number(b.dataset.option)]));const next=document.getElementById('nextQuestion');if(next)next.onclick=nextQuiz}}

function render(){const hash=location.hash||'#/';const [path,query='']=hash.slice(1).split('?');const parts=path.split('/').filter(Boolean);document.title='AlfaCor S.A. | Biblioteca técnica';if(!parts.length||parts[0]==='especialidades'){const params=new URLSearchParams(query);state={specialty:params.get('specialty')||'all',q:params.get('q')||'',category:params.get('category')||'all',brand:params.get('brand')||'all',pdf:params.get('pdf')==='true',asahiType:params.get('asahiType')||'all',guideGroup:params.get('guideGroup')||'all',philipsType:params.get('philipsType')||'all'};if(state.specialty!=='all'&&!SPECIALTIES[state.specialty])state.specialty='all';redrawCatalog()}else if(parts[0]==='producto'){const p=PRODUCTS.find(p=>p.slug===parts[1]);app.innerHTML=p?detail(p):`<section class="container intro"><h1>Producto no encontrado</h1><a class="button primary" href="#/">Ver catálogo</a></section>`;if(p)document.title=p.name+' | AlfaCor';const features=document.getElementById('goFeatures');if(features)features.onclick=e=>{e.preventDefault();document.getElementById('caracteristicas').scrollIntoView({behavior:'smooth',block:'start'})}}else if(parts[0]==='marcas'){app.innerHTML=brandPage()}else if(parts[0]==='estudiar'){app.innerHTML=studyPage();bindQuiz()}else{location.hash='#/';return}document.querySelectorAll('.nav a').forEach(a=>{const selected=(a.dataset.nav==='catalog'&&!['marcas','estudiar'].includes(parts[0]))||a.dataset.nav===parts[0];a.classList.toggle('active',selected);if(selected)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current')});window.scrollTo(0,0)}
window.addEventListener('hashchange',render);render();
